os: linux
language: android

android:
   components:
     - tools
     - platform-tools
     - tools

     - android-25
     - build-tools-25.0.2

     - extra
     - extra-google-m2repository
     - extra-android-m2repository
     - extra-android-support

matrix:
  include:
  - os: osx
    osx_image: xcode8.3
    language: objective_c


install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then echo "your OS X commands here!"; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then echo "your Linux commands here!"; fi

script:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then echo "your OS X commands here!"; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then echo "your Linux commands here!"; fi
