matrix:
  include:
  - os: osx
    osx_image: xcode8.3
    language: objective_c
  - os: linux
    dist: trusty
    language: android

install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then echo "your OS X commands here!"; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then echo "your Linux commands here!"; fi

script:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then echo "your OS X commands here!"; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then echo "your Linux commands here!"; fi
